# Generated by Django 4.0.5 on 2022-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('bnb_balance', models.BigIntegerField(blank=True, null=True)),
                ('bnb_busd', models.BigIntegerField(blank=True, null=True)),
                ('bnb_usdt', models.BigIntegerField(blank=True, null=True)),
                ('eth_balance', models.BigIntegerField(blank=True, null=True)),
                ('eth_usdt', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
