# Generated by Django 4.0.5 on 2022-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='bnb_busd',
            new_name='bnb_busd_balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='bnb_usdt',
            new_name='bnb_usdt_balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='eth_usdt',
            new_name='eth_usdc_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bnb_busd_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bnb_usdt_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eth_usdc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eth_usdt_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eth_usdt_balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
