# Generated by Django 4.0.5 on 2022-07-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_sendedaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bnb_usdt_approved',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bnb_usdt_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eth_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eth_usdc_approved',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eth_usdc_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eth_usdt_approved',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eth_usdt_balance',
        ),
    ]
