# Generated by Django 4.0.5 on 2022-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_remove_wallet_bnb_usdt_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='bnb_busd_approved',
            new_name='busd_approved',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bnb_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bnb_busd_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdt_approved',
            field=models.BooleanField(default=False),
        ),
    ]
