# Generated by Django 4.0.5 on 2022-07-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_rename_bnb_busd_approved_wallet_busd_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('hash', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='TransactionBNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('hash', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
